# Weights & Biases configuration
project: gmcnn-cifar
entity: weber-geoml-harvard-university  # Replace with your entity (username or team name)
tags:
  - GMCNN
  - CIFAR10
log_model: true  # Save model checkpoints to wandb
